[package]
name = "nom-exif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1"
bytes = "1"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"], optional = true }
regex = { version = "1.10", optional = true }

[features]
serialize = ["serde"]
parse_values = ["regex"]

[dev-dependencies]
test-case = "3"
rand = "0.8"
chrono = "0.4"
serde_json = "1.0"
regex = { version = "1.10" }
clap = { version = "4.4", features = ["derive"] }

[[example]]
name = "rexiftool"
# required-features = ["serialize"]
